apiVersion: chainsaw.kyverno.io/v1alpha1
kind: Test
metadata:
  name: example
spec:
  steps:
    - try:
        - apply:
            file: crossplane-resources/xrd/application.yaml
        - apply:
            file: crossplane-resources/composition/application-composition.yaml
        - sleep:
            duration: 5m
        - apply:
            file: crossplane-resources/application-70740.yaml
        # - apply:
        #     file: pod.yaml
        - script:
            timeout: 15m
            content: |
              kubectl wait --for=condition=Ready application/test  --timeout=15m
        # - script:
        #     timeout: 15m
        #     content: |
        #       kubectl wait --for=condition=Synced application/test  --timeout=15m
        - script:
            timeout: 5m
            content: |
              kubectl wait --for=jsonpath='{.status.phase}'=Active ns/notest-ns-dev  --timeout=15m
        - get:
            apiVersion: v1
            kind: Namespace
            name: notest-ns-dev
        - get:
            apiVersion: apps/v1
            kind: Deployment
            name: wrong
            namespace: notest-ns-dev
        - delete:
            file: crossplane-resources/application-70740.yaml
        - sleep:
            duration: 2m
      catch:
        - script:
            timeout: 5m
            content: |
              kubectl get po -n crossplane-system
        - script:
            timeout: 5m
            content: |
              kubectl get pkg
        - script:
            timeout: 5m
            content: |
              kubectl get object
