apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: application-composition
spec:
  compositeTypeRef:
    apiVersion: arpan.io/v1alpha1
    kind: XApplication
  resources:
    - name: namespace
      base:
        apiVersion: kubernetes.crossplane.io/v1alpha2
        kind: Object
        spec:
          providerConfigRef:
            name: kubernetes-provider
          forProvider:
            manifest:
              apiVersion: v1
              kind: Namespace
      patches:
        - type: CombineFromComposite
          combine:
            variables:
              - fromFieldPath: spec.nsName
            strategy: string
            string:
              fmt: "%s-ns-dev"
          toFieldPath: metadata.name
    - name: Deployment
      base:
        apiVersion: kubernetes.crossplane.io/v1alpha2
        kind: Object
        spec:
          providerConfigRef:
            name: kubernetes-provider
          forProvider:
            manifest:
              apiVersion: apps/v1
              kind: Deployment
              metadata:
                name: wrong
                namespace: default
              spec:
                replicas: 1
                template:
                  spec:
                    containers:
                      - name: nginx
                        image: nginx:1.14.2
                        ports:
                          - containerPort: 80
      patches:
        - type: CombineFromComposite
          combine:
            variables:
              - fromFieldPath: spec.nsName
            strategy: string
            string:
              fmt: "%s-ns-dev"
          toFieldPath: spec.references[0].dependsOn.name
        - type: CombineFromComposite
          combine:
            variables:
              - fromFieldPath: spec.nsName
            strategy: string
            string:
              fmt: "%s-ns-dev"
          toFieldPath: spec.forProvider.manifest.metadata.namespace
        - type: CombineFromComposite
          combine:
            variables:
              - fromFieldPath: spec.deploymentConfig.name
            strategy: string
            string:
              fmt: "%s-deploy-dev"
          toFieldPath: metadata.name
        - fromFieldPath: spec.deploymentConfig.replicas
          toFieldPath: spec.forProvider.manifest.spec.replicas
        - fromFieldPath: spec.deploymentConfig.name
          toFieldPath: spec.forProvider.manifest.spec.selector.matchLabels.app
        - fromFieldPath: spec.deploymentConfig.name
          toFieldPath: spec.forProvider.manifest.spec.template.metadata.labels.app
